# Generated by Django 6.0.2 on 2026-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('school_admin', 'School admin')], max_length=20)),
                ('school', models.CharField(max_length=160)),
                ('quote', models.TextField()),
                ('quote_uz', models.TextField(blank=True)),
                ('quote_ru', models.TextField(blank=True)),
                ('quote_en', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_uz', models.CharField(blank=True, max_length=180)),
                ('title_ru', models.CharField(blank=True, max_length=180)),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('reward', models.CharField(max_length=180)),
                ('reward_uz', models.CharField(blank=True, max_length=180)),
                ('reward_ru', models.CharField(blank=True, max_length=180)),
                ('reward_en', models.CharField(blank=True, max_length=180)),
                ('deadline', models.DateTimeField()),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'deadline', '-created_at'],
            },
        ),
    ]
