# Generated by Django 6.0.2 on 2026-03-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_programme_studyfield_department_studyfield_programme'),
        ('subjects', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='fields.programme'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
