# Generated by Django 6.0.2 on 2026-03-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='short_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='folder',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='strict_structure',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
