# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        ('quizzes', '0002_alter_choice_options_choice_image_url_choice_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='apply_to_all_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_fields',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='fields.studyfield'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_marks',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Practice Quiz'), ('live', 'Live Quiz'), ('exam', 'Exam Mode'), ('assignment', 'Assignment Quiz'), ('timed_test', 'Timed Test')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
