# Generated by Django 6.0.2 on 2026-03-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_seed_study_fields'),
        ('quizzes', '0004_questionbank_quizquestion'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='subjects.topic'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_answers_after_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_quizzes', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='subjects.topic'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='unit_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('mcq_multiple', 'Multiple Correct'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Practice Quiz'), ('live', 'Live Quiz'), ('exam', 'Exam Mode'), ('class_test', 'Class Test'), ('midterm', 'Midterm'), ('final', 'Final Exam'), ('assignment', 'Assignment Quiz'), ('timed_test', 'Timed Test')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_entries', to='fields.studyfield'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_entries', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_entries', to='subjects.topic'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_bank_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_links', to='quizzes.questionbank'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_links', to='quizzes.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
    ]
