# Generated by Django 6.0.2 on 2026-03-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_subject_ref_question_topic_ref_and_more'),
        ('subjects', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='subjects.module'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_entries', to='subjects.module'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='subjects.module'),
        ),
    ]
