# Generated by Django 6.0.2 on 2026-03-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_seed_study_fields'),
        ('quizzes', '0006_question_module_ref_questionbank_module_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='target_field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_quizzes', to='fields.studyfield'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_section',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_semester_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_semester_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
