# Generated by Django 6.0.2 on 2026-03-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_programme_studyfield_department_studyfield_programme'),
        ('quizzes', '0007_quiz_target_field_of_study_quiz_target_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='target_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_quizzes', to='fields.programme'),
        ),
    ]
