# Generated by Django 6.0.2 on 2026-02-27 15:43

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_seed_demo_data'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='code',
            field=models.CharField(default=games.models.make_code, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question'], name='games_attem_questio_e8d944_idx'),
        ),
    ]
