# Generated by Django 6.0.2 on 2026-03-03 10:37

import uuid

import games.models
from django.conf import settings
from django.db import migrations, models


def ensure_unique_reconnect_tokens(apps, schema_editor):
    Player = apps.get_model('games', 'Player')
    used_tokens_by_session = {}

    for player in Player.objects.order_by('session_id', 'id'):
        session_tokens = used_tokens_by_session.setdefault(player.session_id, set())
        token = (getattr(player, 'reconnect_token', '') or '').strip()

        if not token or token in session_tokens:
            token = uuid.uuid4().hex
            while token in session_tokens:
                token = uuid.uuid4().hex
            player.reconnect_token = token
            player.save(update_fields=['reconnect_token'])

        session_tokens.add(token)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamesession_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_question_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='avatar-1', max_length=32),
        ),
        migrations.AddField(
            model_name='player',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='join_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='reconnect_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['session', 'client_id'], name='games_playe_session_9c1f81_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['session', 'join_ip'], name='games_playe_session_ac5463_idx'),
        ),
        migrations.RunPython(ensure_unique_reconnect_tokens, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name='player',
            name='reconnect_token',
            field=models.CharField(db_index=True, default=games.models.make_reconnect_token, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('session', 'reconnect_token'), name='uniq_player_session_reconnect'),
        ),
    ]
