# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesession_current_question_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='duration_taken',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='pass_fail_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attempt',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
