# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_attempt_exam_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
