# Generated by Django 6.0.2 on 2026-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_player_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic Mode'), ('speed', 'Speed Mode'), ('team', 'Team Mode'), ('battle', 'Battle Mode'), ('survival', 'Survival Mode'), ('treasure', 'Treasure Mode')], default='classic', max_length=50),
        ),
    ]
