from django.urls import path

from .views import (
    EasiestQuestionsView,
    FieldWisePerformanceView,
    HardestQuestionsView,
    HighestScorerView,
    LowestScorerView,
    ModuleWisePerformanceView,
    QuestionAccuracyAnalyticsView,
    QuizWisePerformanceView,
    RecentAttemptsView,
    SectionPerformanceView,
    SemesterCodePerformanceView,
    SemesterNumberPerformanceView,
    SubjectPerformanceSummaryView,
    SubjectWisePerformanceView,
    TeacherLeaderboardView,
    TeacherScoreSummaryView,
    TopicWisePerformanceView,
)

urlpatterns = [
    path('analytics/leaderboard', TeacherLeaderboardView.as_view(), name='analytics-leaderboard-no-slash'),
    path('analytics/leaderboard/', TeacherLeaderboardView.as_view(), name='analytics-leaderboard'),
    path('analytics/summary', TeacherScoreSummaryView.as_view(), name='analytics-summary-no-slash'),
    path('analytics/summary/', TeacherScoreSummaryView.as_view(), name='analytics-summary'),
    path('analytics/highest-scorer', HighestScorerView.as_view(), name='analytics-highest-no-slash'),
    path('analytics/highest-scorer/', HighestScorerView.as_view(), name='analytics-highest'),
    path('analytics/lowest-scorer', LowestScorerView.as_view(), name='analytics-lowest-no-slash'),
    path('analytics/lowest-scorer/', LowestScorerView.as_view(), name='analytics-lowest'),
    path('analytics/field-performance', FieldWisePerformanceView.as_view(), name='analytics-field-performance-no-slash'),
    path('analytics/field-performance/', FieldWisePerformanceView.as_view(), name='analytics-field-performance'),
    path('analytics/semester-code-performance', SemesterCodePerformanceView.as_view(), name='analytics-semester-code-performance-no-slash'),
    path('analytics/semester-code-performance/', SemesterCodePerformanceView.as_view(), name='analytics-semester-code-performance'),
    path('analytics/semester-performance', SemesterNumberPerformanceView.as_view(), name='analytics-semester-performance-no-slash'),
    path('analytics/semester-performance/', SemesterNumberPerformanceView.as_view(), name='analytics-semester-performance'),
    path('analytics/section-performance', SectionPerformanceView.as_view(), name='analytics-section-performance-no-slash'),
    path('analytics/section-performance/', SectionPerformanceView.as_view(), name='analytics-section-performance'),
    path('analytics/subject-performance', SubjectWisePerformanceView.as_view(), name='analytics-subject-performance-no-slash'),
    path('analytics/subject-performance/', SubjectWisePerformanceView.as_view(), name='analytics-subject-performance'),
    path('analytics/topic-performance', TopicWisePerformanceView.as_view(), name='analytics-topic-performance-no-slash'),
    path('analytics/topic-performance/', TopicWisePerformanceView.as_view(), name='analytics-topic-performance'),
    path('analytics/module-performance', ModuleWisePerformanceView.as_view(), name='analytics-module-performance-no-slash'),
    path('analytics/module-performance/', ModuleWisePerformanceView.as_view(), name='analytics-module-performance'),
    path('analytics/by-module', ModuleWisePerformanceView.as_view(), name='analytics-by-module-no-slash'),
    path('analytics/by-module/', ModuleWisePerformanceView.as_view(), name='analytics-by-module'),
    path('analytics/by-subject', SubjectWisePerformanceView.as_view(), name='analytics-by-subject-no-slash'),
    path('analytics/by-subject/', SubjectWisePerformanceView.as_view(), name='analytics-by-subject'),
    path('analytics/by-topic', TopicWisePerformanceView.as_view(), name='analytics-by-topic-no-slash'),
    path('analytics/by-topic/', TopicWisePerformanceView.as_view(), name='analytics-by-topic'),
    path('analytics/by-quiz', QuizWisePerformanceView.as_view(), name='analytics-by-quiz-no-slash'),
    path('analytics/by-quiz/', QuizWisePerformanceView.as_view(), name='analytics-by-quiz'),
    path('analytics/subject-summary', SubjectPerformanceSummaryView.as_view(), name='analytics-subject-summary-no-slash'),
    path('analytics/subject-summary/', SubjectPerformanceSummaryView.as_view(), name='analytics-subject-summary'),
    path('analytics/question-accuracy', QuestionAccuracyAnalyticsView.as_view(), name='analytics-question-accuracy-no-slash'),
    path('analytics/question-accuracy/', QuestionAccuracyAnalyticsView.as_view(), name='analytics-question-accuracy'),
    path('analytics/hardest-questions', HardestQuestionsView.as_view(), name='analytics-hardest-questions-no-slash'),
    path('analytics/hardest-questions/', HardestQuestionsView.as_view(), name='analytics-hardest-questions'),
    path('analytics/easiest-questions', EasiestQuestionsView.as_view(), name='analytics-easiest-questions-no-slash'),
    path('analytics/easiest-questions/', EasiestQuestionsView.as_view(), name='analytics-easiest-questions'),
    path('analytics/recent-attempts', RecentAttemptsView.as_view(), name='analytics-recent-attempts-no-slash'),
    path('analytics/recent-attempts/', RecentAttemptsView.as_view(), name='analytics-recent-attempts'),
]
