# Generated by Django 6.0.2 on 2026-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_seed_study_fields'),
        ('users', '0002_university_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_fields',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='fields.studyfield'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_semester_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_semester_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='semester_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='semester_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
